# Generated by Django 5.2.5 on 2025-11-30 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_payment_order_alter_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_trx_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
